# -*- coding: utf-8 -*-
"""IBM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRPFy1rOSFuYT1cVIju0S9fJx0kzqLEf
"""

import google.generativeai as genai

from getpass import getpass
api_key = getpass("Enter your API key: ")



genai.configure(api_key=api_key)

model = genai.GenerativeModel('models/gemini-1.5-flash')

def sdg3_message_generator(prompt_text):
    message_prompt = (
        f'''

You are a creative social media expert dedicated to highlighting critical health issues under SDG 3. Using the problem described here: {prompt_text}, craft a short, impactful social media message (up to 250 characters) that informs or motivates.

The message should:
    • Grab attention right away with a strong opening
    • Use a warm, relatable, and encouraging tone
    • Be brief but meaningful and impactful
    • Include 1 to 3 relevant, trending hashtags focused on health, well-being, or SDG 3

Keep the message genuine and powerful—avoid clichés and generic language. Make sure it educates, inspires, or drives awareness about the health challenge.
'''


    )

    response = model.generate_content(message_prompt)
    message = response.text.strip()

    return message

while True:
    prompt = input('Enter the prompt for SDG 3 message or type Exit to Quit: ')

    if prompt.lower() == 'exit':
        print('Exiting!')
        break
    else:
        message = sdg3_message_generator(prompt)
        print(message)